version: "2.3"

services:
  database:
    build:
      context: .
      target: database
    volumes:
      - db-data:/data/db
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=viewgrade
  api_server:
    depends_on:
      - database

volumes:
  storage:
  db-data:
  api_server_log:
